[project]
name = "oktalogger"
version = "0.1.0"
description = "Polls Okta for audit logs and indexes the logs in AWS OpenSearch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.15",
    "opensearch-py>=2.8.0",
    "requests>=2.32.3",
]
